### ISSUE TITLE
About References

### ISSUE THREAD

**Issue by JiayouYxh** [gialme/listScheduling#1]
Hello, do you have any references for this?

**Comment by gialme** [comment]
I'm sorry, what do you mean?

**Comment by JiayouYxh** [comment]
> Hello, do you have any references for this?
Hello, I mean that can you provide some references on this? Thank you!

**Comment by JiayouYxh** [comment]
Hello, I mean that can you provide some references on this? Thank you!

**Comment by JiayouYxh** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Hello, I mean that can you provide some references about listScheduling?
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                2210274575
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 10/12/2022 04:46，Enrico ***@***.***> wrote： 



I'm sorry, what do you mean?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by gialme** [comment]
> Hello, I mean that can you provide some references on this? Thank you!

I used my professors slides (wich are written in italian) and these ones too: https://www.cs.cmu.edu/afs/cs/academic/class/15745-s11/public/lectures/L17-List-Scheduling.pdf

**Comment by gialme** [comment]
i'm closing it
